language: cpp
os: linux
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install -qq libboost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
